### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/instascrape#10]
**Is your feature request related to a problem? Please describe.**
Want to get some simple unit tests going to make sure nothing critical breaks as changes are made, will continue developing this in the future

**Describe the solution you'd like**
Write some tests for the library

**Describe alternatives you've considered**
N/A

**Additional context**
I'm going to start working on this soon but wouldn't mind help

**Comment by dragid10** [comment]
I'd be open to taking this on!

**Comment by chris-greening** [comment]
Awesome! Go for it man, thanks for contributing

**Comment by dragid10** [comment]
@chris-greening Is there any preferences for testing suites? I typically use pytest myself, but if you have a different preference let me know. 

Also I was planning on creating a test folder like so:

├── LICENSE
├── README.md
├── SECURITY.md
├── docs
├── examples
├── instascrape
├── media
├── pypi.bash
├── requirements.txt
├── setup.py
├── **tests**
└── venv

**Comment by chris-greening** [comment]
Great minds think alike 😎  that was the exact direction I was gonna go
