### ISSUE TITLE
Generate a .csv from the scrape_posts()

### ISSUE THREAD

**Issue by Tayzerdo** [chris-greening/instascrape#109]
Hello,

First of all, amazing job with the updates with the instascraper package, the new updates are so awesome

I have a question

I'm using this code below to retrieve the posts information (I based my self on the Joe biden scrape)

```
from selenium.webdriver import Chrome
from instascrape import Profile, scrape_posts
import pandas as pd
import json

# Creating our webdriver
webdriver = Chrome("chromedriver.exe")

# Scraping Joe Biden's profile
SESSIONID = '....'
headers = {"user-agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Mobile Safari/537.36 Edg/87.0.664.57",
           "cookie": f"sessionid={SESSIONID};"}
Insta = Profile("clicktays")
Insta.scrape(headers=headers)

# Scraping the posts
posts = Insta.get_posts(webdriver=webdriver, amount=2, login_first=True)
scraped, unscraped = scrape_posts(posts, silent=False, headers=headers, pause=10)
```

I saw this code to retrieve the information regarding the post, but I'm having some difficult to try to save the post information into a csv or excel file, or even inside pandas

I had a look around but I couldn't be able to do it as I don't have an expert level of python

can you give me a hand?

**Comment by Xerrion** [comment]
You could just do the following.

```python
posts = Insta.get_posts(
    webdriver=webdriver,
    amount=2,
    login_first=True
    scrape=True,
    scrape_pause=10,
)

for post in posts:
    post.to_csv(f"{post['shortcode']}.csv")
```

But if you are only fetching 2 posts from one account, you could set `scrape_pause=0`, to just let it do it. I normally use 3 seconds and can fetch 1390 posts just fine without being rate limited.

**Comment by Tayzerdo** [comment]
Hey hey Xerrion, thank you so much for the answer.

The amount 2 was just a test to retrieve the data, forgot to take it out when posting here.

So with your code, am I be able to extract the informaiton regarding each post that we take it from the profile?

**Comment by Xerrion** [comment]
Should work by creating a csv file for each post with the scraped content.

**Comment by Tayzerdo** [comment]
Perfect, thanks a lot!!! Just trying here but receiving an error

**InstagramLoginRedirectError: Instagram is redirecting you to the login page instead of the page you are trying to scrape. This could be occuring because you made too many requests too quickly or are not logged into Instagram on your machine. Try passing a valid session ID to the scrape method as a cookie to bypass the login requirement**

So I'll wait a bit to try it again

**Comment by Xerrion** [comment]
Try my solution from issue https://github.com/chris-greening/instascrape/issues/102#issuecomment-794121288, you should then be able to remove the `login=True` param.

**Comment by Tayzerdo** [comment]
Perfect, thanks a lot

**Comment by Tayzerdo** [comment]
Just to understand

I make it with your login way, but on the scrape_tools parts, I created the cookies.json file with the information from the Cookie-editor

Should I still use the webdriver=webdriver? because I already took out the "login=True", and I add on the end a way to save all the posts information inside one file (it will make it easier because I'll export the data to Tableau to make a vizualisation)

```
webdriver = Chrome("chromedriver.exe")

url = "https://www.instagram.com/tayzerdo/"

driver = Chrome()
driver.get(url)  # Needed to fake a login
# Fake login with Cookies
with open("cookies.json", "r", newline="") as data:  # Open cookies.json
    cookies = json.load(data)
    for cookie in cookies:  # Add cookies to driver
        cookie.pop("sameSite")  # Selenium breaks with sameSite
        driver.add_cookie(cookie)  # Add our authorized cookies

SESSIONID = '22718363%3A2Xsj99EcBZxqw9%3A9'
headers = {"user-agent": "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Mobile Safari/537.36 Edg/87.0.664.57",
           "cookie": f"sessionid={SESSIONID};"}


Insta = Profile("tayzerdo")
Insta.scrape(headers=headers)

# Scraping the posts
posts = Insta.get_posts(webdriver=webdriver, amount=2, scrape=True, scrape_pause=10)

a = pd.DataFrame()

for post in posts:
    a=a.append({post['shortcode']:post},ignore_index=True)
```

**Comment by Tayzerdo** [comment]
Now it is working, I just added a try/exception and is working til the moment

```
# Scraping the posts
try:
    posts = Insta.get_posts(webdriver=webdriver, amount=100, login_first=True, scrape=True,scrape_pause=3)
except:
    print("Error with instagram login")
```

Thanks a lot for the help @Xerrion
