### ISSUE TITLE
Downloading stories

### ISSUE THREAD

**Issue by alistvt** [chris-greening/instascrape#111]
Hello everybody

Does this repo have any feature to support story downloading?

**Comment by PierreAndreis** [comment]
not yet https://github.com/chris-greening/instascrape/wiki/Scraped-data-points#reel

**Comment by chris-greening** [comment]
Hey! Super late reply apologies, just doubling back and closing old issues 

Instagram has gotten super strict with what can and can't be done so this likely won't be included in any future updates. Again, apologies on late reply!
