### ISSUE TITLE
future feature annotations is not defined (profile.py, line 1)

### ISSUE THREAD

**Issue by AryaDeepanshu** [chris-greening/instascrape#112]
**Describe the bug**
Heroku cant find latest version of library, latest possible version showed there is 0.6.6 and secondly after installing 0.6.6 version it shows following error:
`

Django Version: | 3.1.7
-- | --
SyntaxError
future feature annotations is not defined (profile.py, line 1)
/app/.heroku/python/lib/python3.6/site-packages/instascrape/scrapers/__init__.py, line 1, in <module>
/app/.heroku/python/bin/python
3.6.13

`

**Expected behavior**
My heroku project must have worked

**Comment by shaklev** [comment]
You are using python 3.6 version , in the docs. explicitly says:

> Minimum Python version
This library currently requires Python 3.7 or higher.
