### ISSUE TITLE
Scrape Only Videos?

### ISSUE THREAD

**Issue by boscacci** [chris-greening/instascrape#115]
**Problem?**
I only need to download videos from IG, not photos. Is there a way I could skip photos while scraping?

**Solution?**
Perhaps a parameter in `get_posts` or `scrape_posts` for `video_only=True` or comparable flag

**Alternatives I've considered:**
https://github.com/drawrowfly/instagram-scraper — not super well maintained!

**Comment by stefco** [comment]
Use `Post.is_video` to check this. See [this example](https://dev.to/chrisgreening/downloading-an-instagram-profile-s-recent-photos-using-python-25b2) linked in the readme.

**Comment by boscacci** [comment]
Thanks!
