### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/instascrape#14]
Add/update details on the [README](../blob/master/README.md) for this project. Feel free to be creative, we want it to be bright, creative, and exciting! I've been kind of following [pandas](https://github.com/pandas-dev/pandas) README for inspiration but other ideas are absolutely welcome

Some ideas to tackle:
- [ ] update Features section to be more comprehensive 
- [ ] add more images/gifs 
- [ ] short snippets/examples 
- [ ] Dependencies section
- [ ] badge(s) that add something meaningful to understanding this repo  
- [ ] emojis..... lots of emojis
- [ ] etc!

Really open ended, feel free to comment/submit a PR with ideas that you feel would enhance the README for this project

**Comment by tarob0ba** [comment]
Hi, this is my first time contributing to open source. Can you assign me this?

**Comment by tarob0ba** [comment]
- [ ] update Features section to be more comprehensive
- [ ] add more images/gifs
- [ ] short snippets/examples
- [x] Dependencies section
- [x] badge(s) that add something meaningful to understanding this repo
- [x] emojis... lots of emojis
- [x] fixed a typo

I didn't make many significant changes, just added a dependencies section with the pip commands to install each library, with a few small tweaks. Libraries taken from dependencies.txt

**Comment by tarob0ba** [comment]
Creating a PR now...

**Comment by tarob0ba** [comment]
PR created, will sit tight and do other stuff.

**Comment by tarob0ba** [comment]
Wrote a demo program that looks at the profile data of Google and puts it into a CSV using Pandas. Would you like me to add its source to the readme as a supplement to the profile section under features?

**Comment by chris-greening** [comment]
I love to hear it!!! There's actually an examples folder that I think this would be perfect for if you want to add it as a dedicated file into that directory! Thanks so much for the contributions ❤️

**Comment by tarob0ba** [comment]
You're welcome, I'll make a pull request with the file uploaded. Feel free to look at the source; I had to do it in multiple steps in order to achieve the end goal. How would I incorporate black styling to match everything else?

**Comment by tarob0ba** [comment]
PR created! 😁 
I love this project and will continue to contribute in any way I can!

**Comment by chris-greening** [comment]
For the black styling you can do `pip install black` and then navigate to the root directory and type `black .` and that's it!!! I'm not too worried about enforcing black styling right now so if you don't do it on your PR's, no worries

I'm honestly really glad to hear you like the project though lol, this is my first open source and I'd love for people to get use out of it

**Comment by tarob0ba** [comment]
Might make another screenshot / script analyzing a random hashtag and plotting it using MatPlotLib. Stay tuned!

**Comment by tarob0ba** [comment]
Me, realizing that already exists: 😂

**Comment by chris-greening** [comment]
@beckettnormington Speaking of hashtag scripts though, I have a real world hashtag analysis program that uses instascrape [here](https://github.com/chris-greening/hashtag-analysis) if you wanna check that out. The plan is to launch it on PythonAnywhere but that's been sidelined until I can figure out how to solve Issue #9 lol but it works great otherwise if you want to tinker with it

**Comment by tarob0ba** [comment]
Alrighty, will check that out. Thanks again! ❤️

**Comment by PriyanshTri** [comment]
can I help with this issue?

**Comment by chris-greening** [comment]
@PriyanshTri go for it! Feel free to submit a PR and I'll give it a look 😄

**Comment by beckettnormington** [comment]
I'm gonna be working on making an IPython version of the CSV Scraper.

**Comment by tarob0ba** [comment]
I made a badge that **might** interest you. Details: https://github.com/chatter-social/chatterware

**Comment by tarob0ba** [comment]
Anything that I can improve?

**Comment by chris-greening** [comment]
> Anything that I can improve?

@beckettnormington I'm doing a massive update that's going to greatly improve the library but introduce a ton of breaking changes so I wouldn't want any work you do to be outdated almost immediately lol, check back in a day or two though and I'll let you know!

**Comment by tarob0ba** [comment]
Alrighty, thank you!

**Comment by tarob0ba** [comment]
Might update README's Table of Contents by removing the link to the non-existing dependencies section and send a PR.

**Comment by chris-greening** [comment]
> Might update README's Table of Contents by removing the link tot he non-existing dependencies section and send a PR.

@beckettnormington lolol dang forgot to update that, good catch. Could you create a Dependencies section in between Documentation and Contributing that contains links to [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) and [Requests](https://requests.readthedocs.io/en/master/) docs? That'll emphasize that this is a lightweight library for static HTML scraping _only_ and it'll indicate what's primarily under the hood

**Comment by tarob0ba** [comment]
Sure thing, I'll try to get to that tonight or tomorrow.

**Comment by chris-greening** [comment]
> Sure thing, I'll try to get to that tonight or tomorrow.

Sounds good, very appreciative of your help! 😄

**Comment by tarob0ba** [comment]
Attempted to add dependencies section. PR: #33

**Comment by Siddhant-K-code** [comment]
@chris-greening what more things you want in README.md, I can do it for you.

**Comment by Siddhant-K-code** [comment]
!Suggestion we can Line of Code (LOC) with `python : 98.8%`

**Comment by chris-greening** [comment]
> @chris-greening what more things you want in README.md, I can do it for you.

@Siddhant-K-code It's really open ended! I'm just looking to expand it to make it as comprehensive and exciting as possible to the layman to get people interested in the project

maybe add a Features section with short intro's to the `Profile`, `Post`, and `Hashtag` objects? Let me know what ideas you have!! I'd love to hear them

**Comment by tarob0ba** [comment]
Anything I can do to help improve any existing materials or new things?

**Comment by chris-greening** [comment]
> Anything I can do to help improve any existing materials or new things?

If there are any ideas you have for new features, feel free to open a new issue to get a dialogue going! I think the README is good for now so I'm gonna close this issue and open some more over the next few days with some ideas I have for improvements so keep an eye out :smile: 

Probably gonna write some more blog posts and refactor some stuff so there'll also be that to look for as well  :smirk:
