### ISSUE TITLE
password

### ISSUE THREAD

**Issue by 89z** [chris-greening/instascrape#143]
Is it possible to login with password?

**Comment by chris-greening** [comment]
It is not, the library is intended as a means for scraping data from publicly available HTML and not so much interacting with Instagram aside from GET requests

**Comment by 89z** [comment]
Not sure if youve used this package (or Instagram site) recently, but they have pretty hard rate limits now. You can still do anonymous requests, but after about 16, you get locked out for many hours.

**Comment by 89z** [comment]
I have an implementation, that can do anonymous or logged in requests:

https://github.com/89z/mech/tree/master/instagram

Its in another language though, but maybe it will be helpful.
