### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/instascrape#18]
Provide simple and/or complex examples showcasing the different ways you can use instascrape. 

Jupyter Notebooks explaining your examples in detail are encouraged but not required!

**Comment by tarob0ba** [comment]
I guess I could give this a shot...

**Comment by Paola351** [comment]
I can provide some examples too :D

**Comment by tarob0ba** [comment]
Working on converting that CSV example to IPython

**Comment by tarob0ba** [comment]
Then getting to an actual example.

**Comment by chris-greening** [comment]
@Paola351 Go for it!!! Feel free to make it as simple/complex as you want, I love to see what people come up with. If you're familiar with Jupyter Notebook and want to do a detailed writeup that would be welcomed but is not mandatory.

**Comment by Paola351** [comment]
Ok! I will code a simple Jupyter notebook able to load the library, load a profile, retrieve the post with maximum number of likes of that profiles, it is ok for you? @chris-greening

**Comment by chris-greening** [comment]
@beckettnormington Your example actually gave me an idea for a [to_csv](https://github.com/chris-greening/instascrape/blob/master/instascrape/json_scraper.py#L107) method so now you can write straight to .csv without the overhead of creating a `pandas.DataFrame` prior. If you want though feel free to continue with your implementation of the DataFrame, I like the emphasis of integrating `pandas` when working with instascrape because of obv data science connotations

**Comment by chris-greening** [comment]
> Ok! I will code a simple Jupyter notebook able to load the library, load a profile, retrieve the post with maximum number of likes of that profiles, it is ok for you? @chris-greening

@Paola351 That would be an awesome example! You'll likely have to implement some sort of dynamic functionality if there are more than like 10 posts on a profile to get all the posts because of AJAX. If you check out [profile_scrape.py](https://github.com/chris-greening/instascrape/blob/master/examples/profile_scrape/dynamic_profile.py) there's a subclass of [Profile](https://github.com/chris-greening/instascrape/blob/master/instascrape/profile.py) that uses [selenium](https://selenium-python.readthedocs.io/) that does exactly that. Feel free to reuse that code or come up with your own implementation!!

**Comment by tarob0ba** [comment]
Alrighty, I'll make 2 versions! I'm currently adding detailed explanations to each snippet / line.

**Comment by tarob0ba** [comment]
First CSV example converted to IPython. Now gonna work on a fun Matplotlib example comparing the Big Tech companies' posts and likes to see which one has the best reception overall.

**Comment by tarob0ba** [comment]
Selenium didn't detect ChromeDriver, so that dampened my plans. 😞

**Comment by chris-greening** [comment]
> Selenium didn't detect ChromeDriver, so that dampened my plans. 😞

@beckettnormington You'll have to download a [chromedriver](https://chromedriver.chromium.org/) compatible with your version of chrome/OS. See [this link](https://stackoverflow.com/questions/42478591/python-selenium-chrome-webdriver) for details

**Comment by tarob0ba** [comment]
I used the latest stable release for Windows 10 and added it to PATH, but it still wasn't detected.

**Comment by chris-greening** [comment]
> I used the latest stable release for Windows 10 and added it to PATH, but it still wasn't detected.

@beckettnormington I've had the same problem in the past, try passing the path to your driver with `selenium.webdriver.Chrome(executable_path=r'C:\path\to\your\chromedriver.exe')`

**Comment by tarob0ba** [comment]
Alright, will try! I converted my Instagram CSV example to IPython. PR: #20

**Comment by Paola351** [comment]
> > Ok! I will code a simple Jupyter notebook able to load the library, load a profile, retrieve the post with maximum number of likes of that profiles, it is ok for you? @chris-greening
> 
> @Paola351 That would be an awesome example! You'll likely have to implement some sort of dynamic functionality if there are more than like 10 posts on a profile to get all the posts because of AJAX. If you check out [profile_scrape.py](https://github.com/chris-greening/instascrape/blob/master/examples/profile_scrape/dynamic_profile.py) there's a subclass of [Profile](https://github.com/chris-greening/instascrape/blob/master/instascrape/profile.py) that uses [selenium](https://selenium-python.readthedocs.io/) that does exactly that. Feel free to reuse that code or come up with your own implementation!!

I've checked that but it seems not working. Once i open the apple page on instagram, neither images are loaded or posts' info retrieved. I think It's a little bit trickier than i though :S

**P.S.**. 
nevermind, i figured it out
