### ISSUE TITLE
Rewrite examples to reflect changes

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/instascrape#29]
There have been recent breaking, backwards incompatible changes and thus, the [examples](https://github.com/chris-greening/instascrape/tree/master/examples) section is outdated and sorely in need of being updated to reflect these changes. 

The changes aren't massive so they shouldn't be hard to fix (just slight syntax changes) but they are certainly broken and in need of updating.

**Comment by Devarsh-leo** [comment]
Can I try?

**Comment by o3661606** [comment]
Will try to fix some (or all) examples
