### ISSUE TITLE
Introduce pre-commit with isort, flake8 & black

### ISSUE THREAD

**Issue by benji011** [chris-greening/instascrape#34]
**Is your feature request related to a problem? Please describe.**
I looked around in the docs but couldn't find anything on formatting or linting so I'm wondering if it's okay to add pre-commit config and format the codebase to a set standard. e.g. lines longer than 120 will be detected by flake8 and then reformatted using Black automatically.

**Describe the solution you'd like**
Automate linting & formatting instead of doing them manually.

**Describe alternatives you've considered**
Manual formatting

**Additional context**
I did something similar like in this PR for another project - https://github.com/MissMeg/home-automation-app/pull/22

Please let me know if this idea is worth implementing (or not) and if i can add this to the changes 👍

**Comment by chris-greening** [comment]
Absolutely!!! That was actually on my laundry list of things to do in the very near future so it's funny that you mention it. Go for it :smirk:
