### ISSUE TITLE
Empty field in scrapped profile

### ISSUE THREAD

**Issue by klabertants** [chris-greening/instascrape#41]
**Describe the bug**
Profile fields after scrapping are empty.

**To Reproduce**

Code 
`profile = Profile("hm")`<br>
`profile.scrape()`<br>
`profile.username`<br>

Gives the output
``
nan
``

**Expected behavior**
Right output (in this case "hm")

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (LTS) x64
 - Python 3.8.5
 - insta-scrape==1.1.0

**Comment by chris-greening** [comment]
Hello @klabertants ! Thanks for opening an issue 

I wasn't able to reproduce the missing field value, it works fine for me. Can you show me what you get in `profile.json_dict`?

**Comment by chris-greening** [comment]
Gonna close this for the time being until more info is provided/someone else has the same issue. Let me know if the issue persists and I will reopen it 👍

**Comment by Cherchercher** [comment]
post.username is nan sometimes. For example: https://www.instagram.com/p/COSzSS4DQNG/ 

works around : post.json_dict['graphql']['shortcode_media']['owner']['username']
