### ISSUE TITLE
Scrape by location id

### ISSUE THREAD

**Issue by Sebsebzen** [chris-greening/instascrape#49]
**Is your feature request related to a problem? Please describe.**
For my project I would like to scrape Instagram media from particular places. I already have found a way to retrieve the place id's.

**Describe the solution you'd like**
Scrape this endpoint: https://www.instagram.com/explore/locations/

**Comment by chris-greening** [comment]
Solid idea! I'll take a look into this later today and see what I can find 😎 From a quick glance at the JSON data served back at these location pages though, I have a good feeling we'll be able to accomplish something meaningful with a Location page scraper

**Comment by Sebsebzen** [comment]
Awesome. Looking forward to it!

**Comment by chris-greening** [comment]
Alright, just pushed this feature in the [v1.4.0](https://github.com/chris-greening/instascrape/releases/tag/v1.4.0) update on GitHub and PyPI. Great idea, thanks for the contribution! I'll look into adding support for scraping the [Location directory](https://www.instagram.com/explore/locations/) pages in the future but for now, check out the version release notes I linked above to see the sample usage.
