### ISSUE TITLE
Why do you make it so difficult?

### ISSUE THREAD

**Issue by UnixCro** [chris-greening/instascrape#72]
I have installed insta-scrape, why can't I just enter it in the terminal as with other projects and take action from there? Why do I have to write a script to use this program?

**Comment by chris-greening** [comment]
Hello,

The purpose of this library is to give developers an easy-to-use API for their own Python scripts, not a CLI. I suggest you go try one of those other projects if a CLI is what you're looking for. 

If you would like to start a following discussion, please use the [Discussions](https://github.com/chris-greening/instascrape/discussions) section.

Regards,
Chris
