### ISSUE TITLE
Generate CSV

### ISSUE THREAD

**Issue by wullish** [chris-greening/instascrape#80]
Hi Chris,

How can I generate the same type of CSV file that you provided? I mean with all informations organized.

Best.

**Comment by chris-greening** [comment]
Hello! I combined `instascrape` with a `pandas.DataFrame` so that I could leverage the `pandas.DataFrame.to_csv` [method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html).

```python
import pandas as pd

# Imagine this is a list of scraped instascrape.Post objects 
list_of_post_objects = [...]

post_dicts = [post.to_dict() for post in list_of_post_objects]
df = pd.DataFrame(post_dicts)
df.to_csv("path/to/data.csv")

```

**Comment by wullish** [comment]
Nice man! Thank you, work like a charm. I'm now going to try to fit this into scikit-learn following your jupyter notebook file.

**Comment by chris-greening** [comment]
Love to hear it 😍 I've been busy with some other projects lately but I've got some hot ideas for scikit-learn and an online data dashboard for analyzing `instascrape` data, keep an eye out for that 😏  

Best of luck! I'd love to see what you come up with in the [Discusssions](https://github.com/chris-greening/instascrape/discussions)
