### ISSUE TITLE
email / followers (not the number of followers, but the list of followers)

### ISSUE THREAD

**Issue by jaeseongpark91** [chris-greening/instascrape#81]
Thank you for sharing this. It's awesome and really helpful. 

I am looking for 'email' and 'list of follower' (not the number of followers) info.

Would it be possible to increase your scraped data points?

Thank you in advance!

**Comment by chris-greening** [comment]
Hello, thanks for the ideas! 😄 

Unfortunately email is no longer possible to scrape as far as I know; it used to be supported but Instagram pulled email visibility from the webapp a couple months ago 😢

As for the list of followers, that's definitely something I was looking into introducing but Instagram was being tricky with some of the tests I tried. I'll do some research in the morning but it might be a while before dedicated support is introduced

**Comment by raviriley** [comment]
+1 on a list of followers (just the username strings in a list would be great), that's the only reason I installed only to realize this can only return the number of followers.

**Comment by skyrover7** [comment]
+1 on list of followers for sure!

**Comment by marcvergees** [comment]
Yes please!!

**Comment by youknowmealredy** [comment]
🙏🏻

**Comment by chris-greening** [comment]
Sorry gang but this feature likely won't come through anytime soon

Instagram has been restricting further and further and making it harder for even simple scrapes. Gonna close this for now 😢
