### ISSUE TITLE
Login to Instagram 

### ISSUE THREAD

**Issue by chris-greening** [chris-greening/instascrape#9]
**Is your feature request related to a problem? Please describe.**
Depending on usage, this library won't work as intended because Instagram seemingly checks cookies to make sure the user isn't a random bot. If using instascrape from a personal computer that has been logged into Instagram before, this doesn't seem to be a problem. Unfortunately, the library breaks if trying to use it from say a remote server that has never logged into Instagram before. 

**Describe the solution you'd like**
Provide a way to bypass these restrictions by either 
- logging into Instagram using `requests.post` or similar lightweight lib 
- come up with a way of spoofing/determining/etc. cookies that Instagram looks for 
- find out how to request JSON or similar data directly from their server
- any other method that just allows users to bypass Instagram restrictions 

**Describe alternatives you've considered**
Considered using selenium to login but I really don't want to force people to install or use selenium, the whole purpose is supposed to be lightweight and selenium has too much overhead and is slow 

**Additional context**
N/A

**Comment by MNISAR** [comment]
I do not think one can bypass the 2 factor authentication. What we can do is that use email as 2-factor authentication and then add a simple code to extract code from email and then login for first time (we do not need to worry for next login). From this ```https://github.com/timgrossmann/InstaPy/blob/master/instapy/login_util.py``` you can see that they have made ```bypass_suspicious_login``` method to do so. It can be used as reference to do so.

**Comment by chris-greening** [comment]
@MNISAR, thanks for the info! Funny that you mention `bypass_suspicious_login`, I was literally just looking at instapy's `login_util.py` like two days ago for inspiration. 

I'm apprehensive of using `selenium` for this project because I want to avoid the overhead of opening any browsers or needing any drivers. The original inspiration for this project was actually so that it could run automated on a remote server and not have to worry about hacking together some sort of virtual display or something to get `selenium` working.

I've caught wind that you might be able to POST request your way through though as recently as 2 months ago with `requests`  (see [here](https://stackoverflow.com/questions/62826727/how-would-i-log-into-instagram-using-beautifulsoup4-and-requests-and-how-would?noredirect=1&lq=1)) but wasn't able to find success in the twenty minutes I spent tinkering with it lol but a lightweight solution or similar is definitely the preferred way of getting in if possible 

Regarding the 2-factor authentication though, I figure that's a bridge we can cross when we get to it. I'm pretty sure Insta has 2-factor turned off by default and I just want to get in under normal circumstances

**Comment by MNISAR** [comment]
Good to hear that my comment was helpful!
Hey also did you check the headless mode in selenium, check [this link](https://www.built.io/blog/run-selenium-tests-in-headless-browser) it says about the benefits of using headless mode in tools such as selenium. (reduces overhead)
One more thing about "remembering login" is using  ```--user-data-dir=chrome-data``` in selenium. It works as if a user is using the chrome and you do not have to login every time. This might reduces suspicious login attempts.

**Comment by chris-greening** [comment]
@MNISAR definitely a solid suggestion, instascrape is a bare bones adaptation of a dynamic scraper I wrote that was Selenium heavy for scraping dynamically rendered Instagram content; it isn't that much of a leap to integrate some optional PhantomJS or headless Chrome action to do that dynamic stuff `requests` just can't do
 
Certainly food for thought moving forward!

**Comment by NivardoX** [comment]
Hey @chris-greening, have you seen [this ](https://github.com/softcoder24/instagram-share-post/blob/master/instagram.py) approach? It had some recent updates. Perhaps is a good way of avoiding selenium and heavier tools.

**Comment by chris-greening** [comment]
> Hey @chris-greening, have you seen [this ](https://github.com/softcoder24/instagram-share-post/blob/master/instagram.py) approach? It had some recent updates. Perhaps is a good way of avoiding selenium and heavier tools.

That's exactly the idea I was going for! Definitely looking to use `requests.post` if it's possible. I'll tinker around with this later today, thanks for the reference 😏

**Comment by NivardoX** [comment]
> 
> 
> > Hey @chris-greening, have you seen [this ](https://github.com/softcoder24/instagram-share-post/blob/master/instagram.py) approach? It had some recent updates. Perhaps is a good way of avoiding selenium and heavier tools.
> 
> That's exactly the idea I was going for! Definitely looking to use `requests.post` if it's possible. I'll tinker around with this later today, thanks for the reference 😏

Awesome, when you start coding this, tag me for help. I would love to help you w this.  😄
